include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - avoid_print
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - prefer_const_constructors_in_immutables
    - avoid_unnecessary_containers
    - sized_box_for_whitespace
    - use_key_in_widget_constructors
    - prefer_single_quotes
    - always_declare_return_types
    - avoid_empty_else
    - prefer_is_empty
    - prefer_is_not_empty
    - avoid_returning_null_for_void
    - constant_identifier_names
    - camel_case_types
    - library_names
    - file_names
    - prefer_final_fields
    - prefer_final_locals
    - unnecessary_this
    - sort_child_properties_last

analyzer:
  errors:
    invalid_annotation_target: ignore
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
